# Generated by Django 4.1.5 on 2023-01-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_Video_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='title of the video')),
                ('description', models.TextField(verbose_name='Description of the video')),
                ('thumbnail_url', models.URLField(max_length=255, verbose_name='Image URL')),
                ('published_on', models.DateTimeField(verbose_name='publishing datetime')),
            ],
        ),
    ]
